/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../../ApiClient';

/**
 * The PaymentRequest model module.
 * @module model/PaymentRequest
 * @version 1.1.0
 */
class PaymentRequest {
    /**
     * Constructs a new <code>PaymentRequest</code>.
     * @alias module:model/PaymentRequest
     * @param orderId {Number} 
     * @param amount {Number} 
     * @param currency {String} 
     */
    constructor(orderId, amount, currency) { 
        
        PaymentRequest.initialize(this, orderId, amount, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId, amount, currency) { 
        obj['orderId'] = orderId;
        obj['amount'] = amount;
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>PaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentRequest} obj Optional instance to populate.
     * @return {module:model/PaymentRequest} The populated <code>PaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentRequest();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('externalTxId')) {
                obj['externalTxId'] = ApiClient.convertToType(data['externalTxId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['externalTxId'] && !(typeof data['externalTxId'] === 'string' || data['externalTxId'] instanceof String)) {
            throw new Error("Expected the field `externalTxId` to be a primitive type in the JSON string but got " + data['externalTxId']);
        }

        return true;
    }


}

PaymentRequest.RequiredProperties = ["orderId", "amount", "currency"];

/**
 * @member {Number} orderId
 */
PaymentRequest.prototype['orderId'] = undefined;

/**
 * @member {Number} amount
 */
PaymentRequest.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
PaymentRequest.prototype['currency'] = undefined;

/**
 * @member {module:model/PaymentRequest.StatusEnum} status
 */
PaymentRequest.prototype['status'] = undefined;

/**
 * @member {String} externalTxId
 */
PaymentRequest.prototype['externalTxId'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PaymentRequest['StatusEnum'] = {

    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "FAILED"
     * @const
     */
    "FAILED": "FAILED"
};



export default PaymentRequest;

