/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../../ApiClient';

/**
 * The PaymentUpdate model module.
 * @module model/PaymentUpdate
 * @version 1.1.0
 */
class PaymentUpdate {
    /**
     * Constructs a new <code>PaymentUpdate</code>.
     * @alias module:model/PaymentUpdate
     */
    constructor() { 
        
        PaymentUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentUpdate} obj Optional instance to populate.
     * @return {module:model/PaymentUpdate} The populated <code>PaymentUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentUpdate();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('externalTxId')) {
                obj['externalTxId'] = ApiClient.convertToType(data['externalTxId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['externalTxId'] && !(typeof data['externalTxId'] === 'string' || data['externalTxId'] instanceof String)) {
            throw new Error("Expected the field `externalTxId` to be a primitive type in the JSON string but got " + data['externalTxId']);
        }

        return true;
    }


}



/**
 * @member {Number} amount
 */
PaymentUpdate.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
PaymentUpdate.prototype['currency'] = undefined;

/**
 * @member {module:model/PaymentUpdate.StatusEnum} status
 */
PaymentUpdate.prototype['status'] = undefined;

/**
 * @member {String} externalTxId
 */
PaymentUpdate.prototype['externalTxId'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PaymentUpdate['StatusEnum'] = {

    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "FAILED"
     * @const
     */
    "FAILED": "FAILED"
};



export default PaymentUpdate;

