/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../../ApiClient';

/**
 * The PaymentResponse model module.
 * @module model/PaymentResponse
 * @version 1.1.0
 */
class PaymentResponse {
    /**
     * Constructs a new <code>PaymentResponse</code>.
     * @alias module:model/PaymentResponse
     * @param orderId {Number} 
     * @param status {module:model/PaymentResponse.StatusEnum} 
     */
    constructor(orderId, status) { 
        
        PaymentResponse.initialize(this, orderId, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId, status) { 
        obj['orderId'] = orderId;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>PaymentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentResponse} obj Optional instance to populate.
     * @return {module:model/PaymentResponse} The populated <code>PaymentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentResponse();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('externalTxId')) {
                obj['externalTxId'] = ApiClient.convertToType(data['externalTxId'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['externalTxId'] && !(typeof data['externalTxId'] === 'string' || data['externalTxId'] instanceof String)) {
            throw new Error("Expected the field `externalTxId` to be a primitive type in the JSON string but got " + data['externalTxId']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

PaymentResponse.RequiredProperties = ["orderId", "status"];

/**
 * @member {Number} orderId
 */
PaymentResponse.prototype['orderId'] = undefined;

/**
 * @member {module:model/PaymentResponse.StatusEnum} status
 */
PaymentResponse.prototype['status'] = undefined;

/**
 * @member {String} externalTxId
 */
PaymentResponse.prototype['externalTxId'] = undefined;

/**
 * @member {String} currency
 */
PaymentResponse.prototype['currency'] = undefined;

/**
 * @member {Number} amount
 */
PaymentResponse.prototype['amount'] = undefined;

/**
 * @member {Date} timestamp
 */
PaymentResponse.prototype['timestamp'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PaymentResponse['StatusEnum'] = {

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "FAILED"
     * @const
     */
    "FAILED": "FAILED",

    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING"
};



export default PaymentResponse;

