/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../ApiClient";
import PaymentResponse from "../model/PaymentResponse";
import PaymentStatusResponse from '../model/PaymentStatusResponse';

export const PAYMENTS_CAPABILITIES = {
    fields: {
        orderId: ["EQUAL"],
        status: ["EQUAL"],
        since: ["EQUAL", "GREATER_THAN", "GREATER_THAN_OR_EQUAL"]
    },
    priority: ["orderId", "status", "since"],
    multiCallFields: ["orderId"]
};

export const FILTER_MAPPING = {
    timestamp: "since"
};

/**
* Default service.
* @module api/PaymentsApi
* @version 1.0.0
*/
export default class PaymentsApi {

        /**
        * Constructs a new PaymentsApi. 
        * @alias module:api/PaymentsApi
        * @class
        * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
        * default to {@link module:ApiClient#instance} if unspecified.
        */
        constructor(apiClient) {
            this.apiClient = apiClient || new ApiClient(PAYMENTS_URL);
        }
    
    
        /**
         * Callback function to receive the result of the createPayment operation.
         * @callback module:api/PaymentsApi~createPaymentCallback
         * @param {String} error Error message, if any.
         * @param {module:model/PaymentResponse} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */
    
        /**
         * Create a new payment
         * @param {module:model/PaymentRequest} paymentRequest Payment to be created
         * @param {module:api/PaymentsApi~createPaymentCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/PaymentResponse}
         */
        createPayment(paymentRequest, callback) {
          let postBody = paymentRequest;
          // verify the required parameter 'paymentRequest' is set
          if (paymentRequest === undefined || paymentRequest === null) {
            throw new Error("Missing the required parameter 'paymentRequest' when calling createPayment");
          }
    
          let pathParams = {
          };
          let queryParams = {
          };
          let headerParams = {
          };
          let formParams = {
          };
    
          let authNames = [];
          let contentTypes = ['application/json'];
          let accepts = ['application/json'];
          let returnType = PaymentResponse;
          return this.apiClient.callApi(
            '/payments', 'POST',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
          );
        }
    
        /**
         * Callback function to receive the result of the deletePayment operation.
         * @callback module:api/PaymentsApi~deletePaymentCallback
         * @param {String} error Error message, if any.
         * @param data This operation does not return a value.
         * @param {String} response The complete HTTP response.
         */
    
        /**
         * Delete a payment
         * @param {Number} orderId 
         * @param {module:api/PaymentsApi~deletePaymentCallback} callback The callback function, accepting three arguments: error, data, response
         */
        deletePayment(orderId, callback) {
          let postBody = null;
          // verify the required parameter 'orderId' is set
          if (orderId === undefined || orderId === null) {
            throw new Error("Missing the required parameter 'orderId' when calling deletePayment");
          }
    
          let pathParams = {
            'orderId': orderId
          };
          let queryParams = {
          };
          let headerParams = {
          };
          let formParams = {
          };
    
          let authNames = [];
          let contentTypes = [];
          let accepts = [];
          let returnType = null;
          return this.apiClient.callApi(
            '/payments/{orderId}', 'DELETE',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
          );
        }
    
        /**
         * Callback function to receive the result of the getPaymentStatus operation.
         * @callback module:api/PaymentsApi~getPaymentStatusCallback
         * @param {String} error Error message, if any.
         * @param {module:model/PaymentStatusResponse} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */
    
        /**
         * Get payment status
         * @param {Number} orderId 
         * @param {module:api/PaymentsApi~getPaymentStatusCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/PaymentStatusResponse}
         */
        getPaymentStatus(orderId, callback) {
          let postBody = null;
          // verify the required parameter 'orderId' is set
          if (orderId === undefined || orderId === null) {
            throw new Error("Missing the required parameter 'orderId' when calling getPaymentStatus");
          }
    
          let pathParams = {
            'orderId': orderId
          };
          let queryParams = {
          };
          let headerParams = {
          };
          let formParams = {
          };
    
          let authNames = [];
          let contentTypes = [];
          let accepts = ['application/json'];
          let returnType = PaymentStatusResponse;
          return this.apiClient.callApi(
            '/payments/{orderId}/status', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
          );
        }
    
        /**
         * Callback function to receive the result of the listPayments operation.
         * @callback module:api/PaymentsApi~listPaymentsCallback
         * @param {String} error Error message, if any.
         * @param {Array.<module:model/PaymentResponse>} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */
    
        /**
         * List payments with optional filters
         * @param {Object} opts Optional parameters
         * @param {Number} [orderId] 
         * @param {module:model/String} [status] 
         * @param {Date} [since] 
         * @param {module:api/PaymentsApi~listPaymentsCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link Array.<module:model/PaymentResponse>}
         */
        listPayments(opts, callback) {
          opts = opts || {};
          let postBody = null;
    
          let pathParams = {
          };
          let queryParams = {
            'orderId': opts['orderId'],
            'status': opts['status'],
            'since': opts['since']
          };
          let headerParams = {
          };
          let formParams = {
          };
    
          let authNames = [];
          let contentTypes = [];
          let accepts = ['application/json'];
          let returnType = [PaymentResponse];
          return this.apiClient.callApi(
            '/payments', 'GET',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
          );
        }
    
        /**
         * Callback function to receive the result of the partialUpdatePayment operation.
         * @callback module:api/PaymentsApi~partialUpdatePaymentCallback
         * @param {String} error Error message, if any.
         * @param {module:model/PaymentResponse} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */
    
        /**
         * Partially update a payment
         * @param {Number} orderId 
         * @param {Object.<String, Object>} body 
         * @param {module:api/PaymentsApi~partialUpdatePaymentCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/PaymentResponse}
         */
        partialUpdatePayment(orderId, body, callback) {
          let postBody = body;
          // verify the required parameter 'orderId' is set
          if (orderId === undefined || orderId === null) {
            throw new Error("Missing the required parameter 'orderId' when calling partialUpdatePayment");
          }
          // verify the required parameter 'body' is set
          if (body === undefined || body === null) {
            throw new Error("Missing the required parameter 'body' when calling partialUpdatePayment");
          }
    
          let pathParams = {
            'orderId': orderId
          };
          let queryParams = {
          };
          let headerParams = {
          };
          let formParams = {
          };
    
          let authNames = [];
          let contentTypes = ['application/json'];
          let accepts = ['application/json'];
          let returnType = PaymentResponse;
          return this.apiClient.callApi(
            '/payments/{orderId}', 'PATCH',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
          );
        }
    
        /**
         * Callback function to receive the result of the updatePayment operation.
         * @callback module:api/PaymentsApi~updatePaymentCallback
         * @param {String} error Error message, if any.
         * @param {module:model/PaymentResponse} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */
    
        /**
         * Replace an existing payment
         * @param {Number} orderId 
         * @param {module:model/PaymentUpdate} paymentUpdate 
         * @param {module:api/PaymentsApi~updatePaymentCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/PaymentResponse}
         */
        updatePayment(orderId, paymentUpdate, callback) {
          let postBody = paymentUpdate;
          // verify the required parameter 'orderId' is set
          if (orderId === undefined || orderId === null) {
            throw new Error("Missing the required parameter 'orderId' when calling updatePayment");
          }
          // verify the required parameter 'paymentUpdate' is set
          if (paymentUpdate === undefined || paymentUpdate === null) {
            throw new Error("Missing the required parameter 'paymentUpdate' when calling updatePayment");
          }
    
          let pathParams = {
            'orderId': orderId
          };
          let queryParams = {
          };
          let headerParams = {
          };
          let formParams = {
          };
    
          let authNames = [];
          let contentTypes = ['application/json'];
          let accepts = ['application/json'];
          let returnType = PaymentResponse;
          return this.apiClient.callApi(
            '/payments/{orderId}', 'PUT',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null, callback
          );
        }
    

}
