/**
 * Order Issues API
 * API for registering and retrieving order processing issues.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../../ApiClient';

/**
 * The OrderIssueCreateRequest model module.
 * @module model/OrderIssueCreateRequest
 * @version 1.1.0
 */
class OrderIssueCreateRequest {
    /**
     * Constructs a new <code>OrderIssueCreateRequest</code>.
     * @alias module:model/OrderIssueCreateRequest
     * @param orderId {Number} 
     * @param errorCode {String} 
     * @param errorMessage {String} 
     * @param severity {module:model/OrderIssueCreateRequest.SeverityEnum} 
     */
    constructor(orderId, errorCode, errorMessage, severity) { 
        
        OrderIssueCreateRequest.initialize(this, orderId, errorCode, errorMessage, severity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId, errorCode, errorMessage, severity) { 
        obj['orderId'] = orderId;
        obj['errorCode'] = errorCode;
        obj['errorMessage'] = errorMessage;
        obj['severity'] = severity;
    }

    /**
     * Constructs a <code>OrderIssueCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderIssueCreateRequest} obj Optional instance to populate.
     * @return {module:model/OrderIssueCreateRequest} The populated <code>OrderIssueCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderIssueCreateRequest();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderIssueCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderIssueCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrderIssueCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['errorCode'] && !(typeof data['errorCode'] === 'string' || data['errorCode'] instanceof String)) {
            throw new Error("Expected the field `errorCode` to be a primitive type in the JSON string but got " + data['errorCode']);
        }
        // ensure the json data is a string
        if (data['errorMessage'] && !(typeof data['errorMessage'] === 'string' || data['errorMessage'] instanceof String)) {
            throw new Error("Expected the field `errorMessage` to be a primitive type in the JSON string but got " + data['errorMessage']);
        }
        // ensure the json data is a string
        if (data['severity'] && !(typeof data['severity'] === 'string' || data['severity'] instanceof String)) {
            throw new Error("Expected the field `severity` to be a primitive type in the JSON string but got " + data['severity']);
        }

        return true;
    }


}

OrderIssueCreateRequest.RequiredProperties = ["orderId", "errorCode", "errorMessage", "severity"];

/**
 * @member {Number} orderId
 */
OrderIssueCreateRequest.prototype['orderId'] = undefined;

/**
 * @member {String} errorCode
 */
OrderIssueCreateRequest.prototype['errorCode'] = undefined;

/**
 * @member {String} errorMessage
 */
OrderIssueCreateRequest.prototype['errorMessage'] = undefined;

/**
 * @member {module:model/OrderIssueCreateRequest.SeverityEnum} severity
 */
OrderIssueCreateRequest.prototype['severity'] = undefined;





/**
 * Allowed values for the <code>severity</code> property.
 * @enum {String}
 * @readonly
 */
OrderIssueCreateRequest['SeverityEnum'] = {

    /**
     * value: "LOW"
     * @const
     */
    "LOW": "LOW",

    /**
     * value: "MEDIUM"
     * @const
     */
    "MEDIUM": "MEDIUM",

    /**
     * value: "HIGH"
     * @const
     */
    "HIGH": "HIGH",

    /**
     * value: "CRITICAL"
     * @const
     */
    "CRITICAL": "CRITICAL"
};



export default OrderIssueCreateRequest;

