/**
 * Order Issues API
 * API for registering and retrieving order processing issues.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../../ApiClient";
import OrderIssue from '../model/OrderIssue';

export const ORDER_ISSUES_CAPABILITIES = {
  fields: {
    id: ["EQUAL"],
    orderId: ["EQUAL"],
    severity: ["EQUAL"],
    since: ["EQUAL", "GREATER_THAN", "GREATER_THAN_OR_EQUAL"],
    from: ["EQUAL", "GREATER_THAN", "GREATER_THAN_OR_EQUAL"],
    to: ["EQUAL", "LESS_THAN", "LESS_THAN_OR_EQUAL"]
  },

  priority: ["id", "orderId", "severity", "since", "from", "to"],

  multiCallFields: ["orderId"]
};

export const FILTER_MAPPING = {};

/**
* Default service.
* @module api/OrderIssuesApi
* @version 1.1.0
*/
export default class OrderIssuesApi {

  /**
  * Constructs a new OrderIssuesApi. 
  * @alias module:api/OrderIssuesApi
  * @class
  * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
  * default to {@link module:ApiClient#instance} if unspecified.
  */
  constructor(apiClient) {
    this.apiClient = apiClient || new ApiClient(ORDER_ISSUES_URL);
  }


  /**
   * Callback function to receive the result of the issuesByDateGet operation.
   * @callback module:api/OrderIssuesApi~issuesByDateGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<module:model/OrderIssue>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * List issues by timestamp range
   * Returns issues whose timestamp is between the optional 'from' and 'to' parameters.
   * @param {Object} opts Optional parameters
   * @param {Date} [from] Start date-time (inclusive)
   * @param {Date} [to] End date-time (inclusive)
   * @param {module:api/OrderIssuesApi~issuesByDateGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<module:model/OrderIssue>}
   */
  issuesByDateGet(opts, callback) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {
    };
    let queryParams = {
      'from': opts['from'],
      'to': opts['to']
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = [OrderIssue];
    return this.apiClient.callApi(
      '/issues/by-date', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
   * Callback function to receive the result of the issuesGet operation.
   * @callback module:api/OrderIssuesApi~issuesGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<module:model/OrderIssue>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * List all issues
   * @param {module:api/OrderIssuesApi~issuesGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<module:model/OrderIssue>}
   */
  issuesGet(callback) {
    let postBody = null;

    let pathParams = {
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = [OrderIssue];
    return this.apiClient.callApi(
      '/issues', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
   * Callback function to receive the result of the issuesIdDelete operation.
   * @callback module:api/OrderIssuesApi~issuesIdDeleteCallback
   * @param {String} error Error message, if any.
   * @param data This operation does not return a value.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Delete issue by ID
   * @param {Number} id 
   * @param {module:api/OrderIssuesApi~issuesIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
   */
  issuesIdDelete(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error("Missing the required parameter 'id' when calling issuesIdDelete");
    }

    let pathParams = {
      'id': id
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = null;
    return this.apiClient.callApi(
      '/issues/{id}', 'DELETE',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
   * Callback function to receive the result of the issuesIdGet operation.
   * @callback module:api/OrderIssuesApi~issuesIdGetCallback
   * @param {String} error Error message, if any.
   * @param {module:model/OrderIssue} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get issue by ID
   * @param {Number} id 
   * @param {module:api/OrderIssuesApi~issuesIdGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/OrderIssue}
   */
  issuesIdGet(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error("Missing the required parameter 'id' when calling issuesIdGet");
    }

    let pathParams = {
      'id': id
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = OrderIssue;
    return this.apiClient.callApi(
      '/issues/{id}', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
   * Callback function to receive the result of the issuesPost operation.
   * @callback module:api/OrderIssuesApi~issuesPostCallback
   * @param {String} error Error message, if any.
   * @param {module:model/OrderIssue} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Register an order issue
   * Creates a new issue entry for an order failure.
   * @param {module:model/OrderIssueCreateRequest} orderIssueCreateRequest 
   * @param {module:api/OrderIssuesApi~issuesPostCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/OrderIssue}
   */
  issuesPost(orderIssueCreateRequest, callback) {
    let postBody = orderIssueCreateRequest;
    // verify the required parameter 'orderIssueCreateRequest' is set
    if (orderIssueCreateRequest === undefined || orderIssueCreateRequest === null) {
      throw new Error("Missing the required parameter 'orderIssueCreateRequest' when calling issuesPost");
    }

    let pathParams = {
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = ['application/json'];
    let accepts = ['application/json'];
    let returnType = OrderIssue;
    return this.apiClient.callApi(
      '/issues', 'POST',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
   * Callback function to receive the result of the ordersOrderIdIssuesGet operation.
   * @callback module:api/OrderIssuesApi~ordersOrderIdIssuesGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<module:model/OrderIssue>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get issues for a specific order
   * @param {Number} orderId 
   * @param {module:api/OrderIssuesApi~ordersOrderIdIssuesGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<module:model/OrderIssue>}
   */
  ordersOrderIdIssuesGet(orderId, callback) {
    let postBody = null;
    // verify the required parameter 'orderId' is set
    if (orderId === undefined || orderId === null) {
      throw new Error("Missing the required parameter 'orderId' when calling ordersOrderIdIssuesGet");
    }

    let pathParams = {
      'orderId': orderId
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = [OrderIssue];
    return this.apiClient.callApi(
      '/orders/{orderId}/issues', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
     * Partially update an issue
     * @param {Number} id 
     * @param {Object.<String, Object>} body 
     * @param {module:api/DefaultApi~partialUpdateIssueCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderIssue}
     */
    partialUpdateIssue(id, body, callback) {
      let postBody = body;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling partialUpdateIssue");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling partialUpdateIssue");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OrderIssue;
      return this.apiClient.callApi(
        '/issues/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

}
